### PR TITLE
Initial implementation of payment secret and feature bits

### PR DESCRIPTION
**Pull request by junderw**
Still need to write tests.

@alexbosworth #30 

The BOLT11 description is kind of vague. So the conditions for throwing errors etc. are unclear.

### CODE REVIEW

**Comment by junderw** [comment]
See also https://github.com/lightningnetwork/lightning-rfc/pull/747

**Comment by mrfelton** [comment]
Keen to see this one merged. Can't pay to recent lnd nodes without this

**Comment by mrfelton** [comment]
rebased on master

**Comment by junderw** [comment]
This LGTM from a conceptual standpoint.

However, we need to test this. If you could help by gathering some examples and decoding them so we can see if the decoded data makes sense, then we can create some tests from them using the decoded data and modifying them to trigger all the Errors that are in the logic.

**Pull request merged**
