### PR TITLE
Add getTagsObject function

### PR DESCRIPTION
**Pull request by junderw**
Replaces #60 

@dylancom Please review.

### CODE REVIEW

**Comment by dylancom** [comment]
Nice work. Might be an idea to have tagsObject directly available on the decoded obj (next to tags)?

**Comment by junderw** [comment]
Feel free to make a PR to this branch.
I'll leave this open until you figure out what you want to do.

Currently there are a lot of assumptions baked into the tests which I don't want to break.

Before pushing your new PR, locally run `npm ci` to install dependencies and run `npm run lint && npm run coverage` to make sure all the lints, tests, and coverage work on your changes. Then push.

**Comment by dylancom** [comment]
Tried adding a getter but failed to match fixtures.json. I added tagsObject like I suggested and adjusted the tests.

**Comment by dylancom** [comment]
Great!

**Comment by junderw** [comment]
published as v1.4.0

**Pull request merged**
