### PR TITLE
feat: add litecoin support

### PR DESCRIPTION
**Pull request by mrfelton**
Adds basic support for litecoin.

### CODE REVIEW

**Comment by junderw** [comment]
This breaks compatibility with previous versions.

please make sure to run tests before submitting.

if you break an existing test you are likely breaking someone's app if we merge.

Then add a new test that checks your changes.

**Comment by mrfelton** [comment]
@junderw I've updated this PR to ensure that all of the tests pass. I've also updated the documentation with notes as to the new coin types.

I've reworked so that the API is exactly the same as before - just the addition of two new coin types `litecoin` and `litecoin_testnet`.

**Comment by junderw** [comment]
Could you make the dependency explicitly state github?

iirc it implicitly gets the domain from this project's repository setting.

Explicit is better imo

**Comment by mrfelton** [comment]
@junderw I've updated the dependency to reference the full uri.

**Comment by junderw** [comment]
Published as 1.2.1

**Pull request merged**
